title: Ana-Marija Nedić # your name (or website title) here
logo: "/images/photo_amnedic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  contact: amnedic AT iastate DOT edu
theme: jekyll-theme-minimal
google_analytics: G-D1CHWYQ5XQ # your Google Analytics tracking ID here
