title: Ana-Marija Nedić # your name (or website title) here
logo: "/images/photo_amnedic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Contact: amnedic AT umn DOT edu
  <br>
  Connect on <a href="https://www.linkedin.com/in/amnedic/">LinkedIn</a>
  <br>
  List of publications on <a href="https://scholar.google.com/citations?user=G8dpesz0AAAAJ&hl=en">Google Scholar</a>
  <br>
  Codes repositories on <a href="https://github.com/amnedic/">GitHub</a>
theme: jekyll-theme-minimal
