title: Ana-Marija Nedić # your name (or website title) here
logo: "/images/photo_amnedic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student at Iowa State University working with <a href="https://faculty.sites.iastate.edu/porth/people/peter-p-orth">Peter Orth</a> 
  <br><br>
  
theme: jekyll-theme-minimal
